# Codefresh triggers:
# Push commits
version: "1.0"
stages:
  - "clone"
  - "build"
  - "test"
steps:
  main_clone:
    type: "git-clone"
    description: "Cloning main repository..."
    repo: "pinpt/agent"
    revision: "${{CF_BRANCH}}"
    stage: "clone"
  build_alpine:
    title: "Building Docker Image"
    type: "build"
    image_name: "pinpt/agent"
    tag: "${{CF_BRANCH_TAG_NORMALIZED}}"
    dockerfile: "docker/unittests/Dockerfile"
    stage: "build"
  my_unit_tests:
    title: Unit tests
    stage: test
    image: "${{build_alpine}}"
    commands:
      #- ls -la /codefresh/volume/*
      - rm -rf /codefresh/volume/go/src/github.com/pinpt/agent
      - mkdir -p /codefresh/volume/go/src/github.com/pinpt
      - cp -r /codefresh/volume/agent /codefresh/volume/go/src/github.com/pinpt/agent
      - cd /codefresh/volume/go/src/github.com/pinpt/agent
      - GOCACHE=/codefresh/volume/go-cache GOPATH=/codefresh/volume/go CGO_ENABLED=0 go test -v ./... -timeout 1m
      #- ls -la /codefresh/volume/*
