// Code generated by protoc-gen-go. DO NOT EDIT.
// source: defs.proto

package proto

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type ExportObj_DataType int32

const (
	ExportObj_JSON ExportObj_DataType = 0
	ExportObj_AVRO ExportObj_DataType = 1
)

var ExportObj_DataType_name = map[int32]string{
	0: "JSON",
	1: "AVRO",
}

var ExportObj_DataType_value = map[string]int32{
	"JSON": 0,
	"AVRO": 1,
}

func (x ExportObj_DataType) String() string {
	return proto.EnumName(ExportObj_DataType_name, int32(x))
}

func (ExportObj_DataType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_bf10f51bd2cb5547, []int{9, 0}
}

type Empty struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Empty) Reset()         { *m = Empty{} }
func (m *Empty) String() string { return proto.CompactTextString(m) }
func (*Empty) ProtoMessage()    {}
func (*Empty) Descriptor() ([]byte, []int) {
	return fileDescriptor_bf10f51bd2cb5547, []int{0}
}

func (m *Empty) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Empty.Unmarshal(m, b)
}
func (m *Empty) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Empty.Marshal(b, m, deterministic)
}
func (m *Empty) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Empty.Merge(m, src)
}
func (m *Empty) XXX_Size() int {
	return xxx_messageInfo_Empty.Size(m)
}
func (m *Empty) XXX_DiscardUnknown() {
	xxx_messageInfo_Empty.DiscardUnknown(m)
}

var xxx_messageInfo_Empty proto.InternalMessageInfo

type IntegrationInitReq struct {
	ServerId             uint32   `protobuf:"varint,1,opt,name=server_id,json=serverId,proto3" json:"server_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *IntegrationInitReq) Reset()         { *m = IntegrationInitReq{} }
func (m *IntegrationInitReq) String() string { return proto.CompactTextString(m) }
func (*IntegrationInitReq) ProtoMessage()    {}
func (*IntegrationInitReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_bf10f51bd2cb5547, []int{1}
}

func (m *IntegrationInitReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_IntegrationInitReq.Unmarshal(m, b)
}
func (m *IntegrationInitReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_IntegrationInitReq.Marshal(b, m, deterministic)
}
func (m *IntegrationInitReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_IntegrationInitReq.Merge(m, src)
}
func (m *IntegrationInitReq) XXX_Size() int {
	return xxx_messageInfo_IntegrationInitReq.Size(m)
}
func (m *IntegrationInitReq) XXX_DiscardUnknown() {
	xxx_messageInfo_IntegrationInitReq.DiscardUnknown(m)
}

var xxx_messageInfo_IntegrationInitReq proto.InternalMessageInfo

func (m *IntegrationInitReq) GetServerId() uint32 {
	if m != nil {
		return m.ServerId
	}
	return 0
}

type IntegrationExportReq struct {
	IntegrationConfigJson []byte   `protobuf:"bytes,1,opt,name=integration_config_json,json=integrationConfigJson,proto3" json:"integration_config_json,omitempty"`
	XXX_NoUnkeyedLiteral  struct{} `json:"-"`
	XXX_unrecognized      []byte   `json:"-"`
	XXX_sizecache         int32    `json:"-"`
}

func (m *IntegrationExportReq) Reset()         { *m = IntegrationExportReq{} }
func (m *IntegrationExportReq) String() string { return proto.CompactTextString(m) }
func (*IntegrationExportReq) ProtoMessage()    {}
func (*IntegrationExportReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_bf10f51bd2cb5547, []int{2}
}

func (m *IntegrationExportReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_IntegrationExportReq.Unmarshal(m, b)
}
func (m *IntegrationExportReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_IntegrationExportReq.Marshal(b, m, deterministic)
}
func (m *IntegrationExportReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_IntegrationExportReq.Merge(m, src)
}
func (m *IntegrationExportReq) XXX_Size() int {
	return xxx_messageInfo_IntegrationExportReq.Size(m)
}
func (m *IntegrationExportReq) XXX_DiscardUnknown() {
	xxx_messageInfo_IntegrationExportReq.DiscardUnknown(m)
}

var xxx_messageInfo_IntegrationExportReq proto.InternalMessageInfo

func (m *IntegrationExportReq) GetIntegrationConfigJson() []byte {
	if m != nil {
		return m.IntegrationConfigJson
	}
	return nil
}

type IntegrationExportResp struct {
	IntegrationNewConfigJson []byte   `protobuf:"bytes,1,opt,name=integration_new_config_json,json=integrationNewConfigJson,proto3" json:"integration_new_config_json,omitempty"`
	XXX_NoUnkeyedLiteral     struct{} `json:"-"`
	XXX_unrecognized         []byte   `json:"-"`
	XXX_sizecache            int32    `json:"-"`
}

func (m *IntegrationExportResp) Reset()         { *m = IntegrationExportResp{} }
func (m *IntegrationExportResp) String() string { return proto.CompactTextString(m) }
func (*IntegrationExportResp) ProtoMessage()    {}
func (*IntegrationExportResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_bf10f51bd2cb5547, []int{3}
}

func (m *IntegrationExportResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_IntegrationExportResp.Unmarshal(m, b)
}
func (m *IntegrationExportResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_IntegrationExportResp.Marshal(b, m, deterministic)
}
func (m *IntegrationExportResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_IntegrationExportResp.Merge(m, src)
}
func (m *IntegrationExportResp) XXX_Size() int {
	return xxx_messageInfo_IntegrationExportResp.Size(m)
}
func (m *IntegrationExportResp) XXX_DiscardUnknown() {
	xxx_messageInfo_IntegrationExportResp.DiscardUnknown(m)
}

var xxx_messageInfo_IntegrationExportResp proto.InternalMessageInfo

func (m *IntegrationExportResp) GetIntegrationNewConfigJson() []byte {
	if m != nil {
		return m.IntegrationNewConfigJson
	}
	return nil
}

type LastProcessed struct {
	DataStr              string   `protobuf:"bytes,1,opt,name=data_str,json=dataStr,proto3" json:"data_str,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LastProcessed) Reset()         { *m = LastProcessed{} }
func (m *LastProcessed) String() string { return proto.CompactTextString(m) }
func (*LastProcessed) ProtoMessage()    {}
func (*LastProcessed) Descriptor() ([]byte, []int) {
	return fileDescriptor_bf10f51bd2cb5547, []int{4}
}

func (m *LastProcessed) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LastProcessed.Unmarshal(m, b)
}
func (m *LastProcessed) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LastProcessed.Marshal(b, m, deterministic)
}
func (m *LastProcessed) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LastProcessed.Merge(m, src)
}
func (m *LastProcessed) XXX_Size() int {
	return xxx_messageInfo_LastProcessed.Size(m)
}
func (m *LastProcessed) XXX_DiscardUnknown() {
	xxx_messageInfo_LastProcessed.DiscardUnknown(m)
}

var xxx_messageInfo_LastProcessed proto.InternalMessageInfo

func (m *LastProcessed) GetDataStr() string {
	if m != nil {
		return m.DataStr
	}
	return ""
}

type ExportStartedReq struct {
	ModelType            string   `protobuf:"bytes,1,opt,name=model_type,json=modelType,proto3" json:"model_type,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ExportStartedReq) Reset()         { *m = ExportStartedReq{} }
func (m *ExportStartedReq) String() string { return proto.CompactTextString(m) }
func (*ExportStartedReq) ProtoMessage()    {}
func (*ExportStartedReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_bf10f51bd2cb5547, []int{5}
}

func (m *ExportStartedReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ExportStartedReq.Unmarshal(m, b)
}
func (m *ExportStartedReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ExportStartedReq.Marshal(b, m, deterministic)
}
func (m *ExportStartedReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ExportStartedReq.Merge(m, src)
}
func (m *ExportStartedReq) XXX_Size() int {
	return xxx_messageInfo_ExportStartedReq.Size(m)
}
func (m *ExportStartedReq) XXX_DiscardUnknown() {
	xxx_messageInfo_ExportStartedReq.DiscardUnknown(m)
}

var xxx_messageInfo_ExportStartedReq proto.InternalMessageInfo

func (m *ExportStartedReq) GetModelType() string {
	if m != nil {
		return m.ModelType
	}
	return ""
}

type ExportStartedResp struct {
	SessionId            string         `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	LastProcessed        *LastProcessed `protobuf:"bytes,2,opt,name=last_processed,json=lastProcessed,proto3" json:"last_processed,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *ExportStartedResp) Reset()         { *m = ExportStartedResp{} }
func (m *ExportStartedResp) String() string { return proto.CompactTextString(m) }
func (*ExportStartedResp) ProtoMessage()    {}
func (*ExportStartedResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_bf10f51bd2cb5547, []int{6}
}

func (m *ExportStartedResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ExportStartedResp.Unmarshal(m, b)
}
func (m *ExportStartedResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ExportStartedResp.Marshal(b, m, deterministic)
}
func (m *ExportStartedResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ExportStartedResp.Merge(m, src)
}
func (m *ExportStartedResp) XXX_Size() int {
	return xxx_messageInfo_ExportStartedResp.Size(m)
}
func (m *ExportStartedResp) XXX_DiscardUnknown() {
	xxx_messageInfo_ExportStartedResp.DiscardUnknown(m)
}

var xxx_messageInfo_ExportStartedResp proto.InternalMessageInfo

func (m *ExportStartedResp) GetSessionId() string {
	if m != nil {
		return m.SessionId
	}
	return ""
}

func (m *ExportStartedResp) GetLastProcessed() *LastProcessed {
	if m != nil {
		return m.LastProcessed
	}
	return nil
}

type ExportDoneReq struct {
	SessionId            string         `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	LastProcessed        *LastProcessed `protobuf:"bytes,2,opt,name=last_processed,json=lastProcessed,proto3" json:"last_processed,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *ExportDoneReq) Reset()         { *m = ExportDoneReq{} }
func (m *ExportDoneReq) String() string { return proto.CompactTextString(m) }
func (*ExportDoneReq) ProtoMessage()    {}
func (*ExportDoneReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_bf10f51bd2cb5547, []int{7}
}

func (m *ExportDoneReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ExportDoneReq.Unmarshal(m, b)
}
func (m *ExportDoneReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ExportDoneReq.Marshal(b, m, deterministic)
}
func (m *ExportDoneReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ExportDoneReq.Merge(m, src)
}
func (m *ExportDoneReq) XXX_Size() int {
	return xxx_messageInfo_ExportDoneReq.Size(m)
}
func (m *ExportDoneReq) XXX_DiscardUnknown() {
	xxx_messageInfo_ExportDoneReq.DiscardUnknown(m)
}

var xxx_messageInfo_ExportDoneReq proto.InternalMessageInfo

func (m *ExportDoneReq) GetSessionId() string {
	if m != nil {
		return m.SessionId
	}
	return ""
}

func (m *ExportDoneReq) GetLastProcessed() *LastProcessed {
	if m != nil {
		return m.LastProcessed
	}
	return nil
}

type SendExportedReq struct {
	SessionId            string       `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Objs                 []*ExportObj `protobuf:"bytes,3,rep,name=objs,proto3" json:"objs,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *SendExportedReq) Reset()         { *m = SendExportedReq{} }
func (m *SendExportedReq) String() string { return proto.CompactTextString(m) }
func (*SendExportedReq) ProtoMessage()    {}
func (*SendExportedReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_bf10f51bd2cb5547, []int{8}
}

func (m *SendExportedReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SendExportedReq.Unmarshal(m, b)
}
func (m *SendExportedReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SendExportedReq.Marshal(b, m, deterministic)
}
func (m *SendExportedReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SendExportedReq.Merge(m, src)
}
func (m *SendExportedReq) XXX_Size() int {
	return xxx_messageInfo_SendExportedReq.Size(m)
}
func (m *SendExportedReq) XXX_DiscardUnknown() {
	xxx_messageInfo_SendExportedReq.DiscardUnknown(m)
}

var xxx_messageInfo_SendExportedReq proto.InternalMessageInfo

func (m *SendExportedReq) GetSessionId() string {
	if m != nil {
		return m.SessionId
	}
	return ""
}

func (m *SendExportedReq) GetObjs() []*ExportObj {
	if m != nil {
		return m.Objs
	}
	return nil
}

type ExportObj struct {
	DataType             ExportObj_DataType `protobuf:"varint,1,opt,name=data_type,json=dataType,proto3,enum=proto.ExportObj_DataType" json:"data_type,omitempty"`
	Data                 []byte             `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *ExportObj) Reset()         { *m = ExportObj{} }
func (m *ExportObj) String() string { return proto.CompactTextString(m) }
func (*ExportObj) ProtoMessage()    {}
func (*ExportObj) Descriptor() ([]byte, []int) {
	return fileDescriptor_bf10f51bd2cb5547, []int{9}
}

func (m *ExportObj) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ExportObj.Unmarshal(m, b)
}
func (m *ExportObj) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ExportObj.Marshal(b, m, deterministic)
}
func (m *ExportObj) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ExportObj.Merge(m, src)
}
func (m *ExportObj) XXX_Size() int {
	return xxx_messageInfo_ExportObj.Size(m)
}
func (m *ExportObj) XXX_DiscardUnknown() {
	xxx_messageInfo_ExportObj.DiscardUnknown(m)
}

var xxx_messageInfo_ExportObj proto.InternalMessageInfo

func (m *ExportObj) GetDataType() ExportObj_DataType {
	if m != nil {
		return m.DataType
	}
	return ExportObj_JSON
}

func (m *ExportObj) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

type ExportGitRepoReq struct {
	RepoId               string   `protobuf:"bytes,1,opt,name=repo_id,json=repoId,proto3" json:"repo_id,omitempty"`
	Url                  string   `protobuf:"bytes,2,opt,name=url,proto3" json:"url,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ExportGitRepoReq) Reset()         { *m = ExportGitRepoReq{} }
func (m *ExportGitRepoReq) String() string { return proto.CompactTextString(m) }
func (*ExportGitRepoReq) ProtoMessage()    {}
func (*ExportGitRepoReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_bf10f51bd2cb5547, []int{10}
}

func (m *ExportGitRepoReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ExportGitRepoReq.Unmarshal(m, b)
}
func (m *ExportGitRepoReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ExportGitRepoReq.Marshal(b, m, deterministic)
}
func (m *ExportGitRepoReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ExportGitRepoReq.Merge(m, src)
}
func (m *ExportGitRepoReq) XXX_Size() int {
	return xxx_messageInfo_ExportGitRepoReq.Size(m)
}
func (m *ExportGitRepoReq) XXX_DiscardUnknown() {
	xxx_messageInfo_ExportGitRepoReq.DiscardUnknown(m)
}

var xxx_messageInfo_ExportGitRepoReq proto.InternalMessageInfo

func (m *ExportGitRepoReq) GetRepoId() string {
	if m != nil {
		return m.RepoId
	}
	return ""
}

func (m *ExportGitRepoReq) GetUrl() string {
	if m != nil {
		return m.Url
	}
	return ""
}

func init() {
	proto.RegisterEnum("proto.ExportObj_DataType", ExportObj_DataType_name, ExportObj_DataType_value)
	proto.RegisterType((*Empty)(nil), "proto.Empty")
	proto.RegisterType((*IntegrationInitReq)(nil), "proto.IntegrationInitReq")
	proto.RegisterType((*IntegrationExportReq)(nil), "proto.IntegrationExportReq")
	proto.RegisterType((*IntegrationExportResp)(nil), "proto.IntegrationExportResp")
	proto.RegisterType((*LastProcessed)(nil), "proto.LastProcessed")
	proto.RegisterType((*ExportStartedReq)(nil), "proto.ExportStartedReq")
	proto.RegisterType((*ExportStartedResp)(nil), "proto.ExportStartedResp")
	proto.RegisterType((*ExportDoneReq)(nil), "proto.ExportDoneReq")
	proto.RegisterType((*SendExportedReq)(nil), "proto.SendExportedReq")
	proto.RegisterType((*ExportObj)(nil), "proto.ExportObj")
	proto.RegisterType((*ExportGitRepoReq)(nil), "proto.ExportGitRepoReq")
}

func init() { proto.RegisterFile("defs.proto", fileDescriptor_bf10f51bd2cb5547) }

var fileDescriptor_bf10f51bd2cb5547 = []byte{
	// 536 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x53, 0xcd, 0x6f, 0x12, 0x41,
	0x14, 0x77, 0xe5, 0x73, 0x1f, 0x50, 0xf1, 0x85, 0x0a, 0x05, 0x35, 0x64, 0xe3, 0x81, 0x78, 0x40,
	0x8b, 0x86, 0x8b, 0xe9, 0xa1, 0xb6, 0x8d, 0xa1, 0x31, 0x60, 0x06, 0xc3, 0x75, 0xb3, 0x74, 0xa7,
	0x04, 0xa4, 0x3b, 0xe3, 0xcc, 0x28, 0x72, 0xf6, 0xcf, 0xf5, 0x9f, 0x30, 0x33, 0xbb, 0xcb, 0x2e,
	0x5b, 0xf4, 0xd6, 0xd3, 0xbc, 0x8f, 0xf9, 0xbd, 0xcf, 0xdf, 0x03, 0xf0, 0xe9, 0xad, 0xec, 0x73,
	0xc1, 0x14, 0xc3, 0x82, 0x79, 0x9c, 0x12, 0x14, 0xae, 0xee, 0xb8, 0xda, 0x3a, 0xa7, 0x80, 0xa3,
	0x40, 0xd1, 0x85, 0xf0, 0xd4, 0x92, 0x05, 0xa3, 0x60, 0xa9, 0x08, 0xfd, 0x8e, 0x1d, 0xb0, 0x25,
	0x15, 0x3f, 0xa9, 0x70, 0x97, 0x7e, 0xcb, 0xea, 0x5a, 0xbd, 0x1a, 0x29, 0x87, 0x86, 0x91, 0xef,
	0x8c, 0xa1, 0x91, 0x82, 0x5c, 0xfd, 0xe2, 0x4c, 0x18, 0xd0, 0x10, 0x9a, 0xcb, 0xc4, 0xee, 0xde,
	0xb0, 0xe0, 0x76, 0xb9, 0x70, 0x57, 0x92, 0x05, 0x26, 0x44, 0x95, 0x1c, 0xa7, 0xdc, 0x17, 0xc6,
	0x7b, 0x2d, 0x59, 0xe0, 0xcc, 0xe0, 0xf8, 0x40, 0x3c, 0xc9, 0xf1, 0x0c, 0x3a, 0xe9, 0x80, 0x01,
	0xdd, 0x1c, 0x08, 0xda, 0x4a, 0x7d, 0x19, 0xd3, 0x4d, 0x2a, 0xee, 0x6b, 0xa8, 0x7d, 0xf6, 0xa4,
	0xfa, 0x22, 0xd8, 0x0d, 0x95, 0x92, 0xfa, 0x78, 0x02, 0x65, 0xdf, 0x53, 0x9e, 0x2b, 0x95, 0x30,
	0x60, 0x9b, 0x94, 0xb4, 0x3e, 0x55, 0xc2, 0x39, 0x85, 0x7a, 0x98, 0x78, 0xaa, 0x3c, 0xa1, 0xa8,
	0xaf, 0xfb, 0x79, 0x01, 0x70, 0xc7, 0x7c, 0xba, 0x76, 0xd5, 0x96, 0xd3, 0x08, 0x60, 0x1b, 0xcb,
	0xd7, 0x2d, 0xa7, 0x0e, 0x83, 0xa7, 0x19, 0x88, 0xe4, 0x1a, 0x23, 0xa9, 0x94, 0xba, 0xdc, 0x68,
	0x72, 0x36, 0xb1, 0x23, 0xcb, 0xc8, 0xc7, 0x0f, 0x70, 0xb4, 0xf6, 0xa4, 0x72, 0x79, 0x5c, 0x53,
	0xeb, 0x71, 0xd7, 0xea, 0x55, 0x06, 0x8d, 0x70, 0x3b, 0xfd, 0xbd, 0x7a, 0x49, 0x6d, 0x9d, 0x56,
	0x9d, 0x6f, 0x50, 0x0b, 0x13, 0x5e, 0xb2, 0x80, 0x46, 0x05, 0x3e, 0x58, 0xb2, 0x19, 0x3c, 0x99,
	0xd2, 0xc0, 0x0f, 0x13, 0xee, 0xe6, 0xf1, 0xbf, 0x74, 0xaf, 0x20, 0xcf, 0xe6, 0x2b, 0xd9, 0xca,
	0x75, 0x73, 0xbd, 0xca, 0xa0, 0x1e, 0x25, 0x09, 0x03, 0x4c, 0xe6, 0x2b, 0x62, 0xbc, 0xce, 0x06,
	0xec, 0x9d, 0x09, 0x87, 0x60, 0x9b, 0x85, 0xec, 0x06, 0x7c, 0x34, 0x38, 0xc9, 0xe2, 0xfa, 0x97,
	0x9e, 0xf2, 0xf4, 0xc0, 0x89, 0x59, 0x9e, 0x96, 0x10, 0x21, 0xaf, 0x65, 0xd3, 0x4f, 0x95, 0x18,
	0xd9, 0x79, 0x09, 0xe5, 0xf8, 0x27, 0x96, 0x21, 0x7f, 0x3d, 0x9d, 0x8c, 0xeb, 0x8f, 0xb4, 0x74,
	0x3e, 0x23, 0x93, 0xba, 0xe5, 0x9c, 0xc5, 0x1b, 0xfe, 0xa4, 0x29, 0xce, 0x99, 0xee, 0xa8, 0x09,
	0x25, 0x41, 0x39, 0x4b, 0xda, 0x29, 0x6a, 0x75, 0xe4, 0x63, 0x1d, 0x72, 0x3f, 0xc4, 0xda, 0xc4,
	0xb7, 0x89, 0x16, 0x07, 0xbf, 0x2d, 0xa8, 0xa4, 0x58, 0x8a, 0x6f, 0x20, 0xaf, 0x8f, 0x05, 0xe3,
	0x7a, 0xef, 0x1f, 0x51, 0xbb, 0x1a, 0xb7, 0xa2, 0x0f, 0x0d, 0x2f, 0xa0, 0x18, 0xe6, 0xc7, 0xce,
	0x7d, 0xc8, 0xee, 0x88, 0xda, 0xcf, 0xff, 0xed, 0x94, 0x7c, 0xf0, 0xc7, 0x82, 0xc2, 0xf9, 0x82,
	0x06, 0x0a, 0x3f, 0xc6, 0x64, 0x88, 0xd8, 0x87, 0xcd, 0xbd, 0xc1, 0x25, 0x34, 0x6e, 0xb7, 0x0e,
	0x3b, 0x24, 0xc7, 0xb7, 0x00, 0x09, 0xa1, 0xb0, 0xb1, 0xf7, 0x2f, 0xe2, 0x58, 0xa6, 0x89, 0xf7,
	0x50, 0x4d, 0xb3, 0x02, 0x9f, 0x45, 0xde, 0x0c, 0x55, 0x32, 0xa8, 0x61, 0x5c, 0x6b, 0x34, 0xfa,
	0x4c, 0xad, 0xc9, 0x42, 0xf6, 0x71, 0xf3, 0xa2, 0x51, 0xde, 0xfd, 0x0d, 0x00, 0x00, 0xff, 0xff,
	0xcb, 0x45, 0x49, 0xd0, 0xc0, 0x04, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// IntegrationClient is the client API for Integration service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type IntegrationClient interface {
	Init(ctx context.Context, in *IntegrationInitReq, opts ...grpc.CallOption) (*Empty, error)
	Export(ctx context.Context, in *IntegrationExportReq, opts ...grpc.CallOption) (*IntegrationExportResp, error)
}

type integrationClient struct {
	cc *grpc.ClientConn
}

func NewIntegrationClient(cc *grpc.ClientConn) IntegrationClient {
	return &integrationClient{cc}
}

func (c *integrationClient) Init(ctx context.Context, in *IntegrationInitReq, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := c.cc.Invoke(ctx, "/proto.Integration/Init", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *integrationClient) Export(ctx context.Context, in *IntegrationExportReq, opts ...grpc.CallOption) (*IntegrationExportResp, error) {
	out := new(IntegrationExportResp)
	err := c.cc.Invoke(ctx, "/proto.Integration/Export", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// IntegrationServer is the server API for Integration service.
type IntegrationServer interface {
	Init(context.Context, *IntegrationInitReq) (*Empty, error)
	Export(context.Context, *IntegrationExportReq) (*IntegrationExportResp, error)
}

func RegisterIntegrationServer(s *grpc.Server, srv IntegrationServer) {
	s.RegisterService(&_Integration_serviceDesc, srv)
}

func _Integration_Init_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IntegrationInitReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IntegrationServer).Init(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Integration/Init",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IntegrationServer).Init(ctx, req.(*IntegrationInitReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Integration_Export_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IntegrationExportReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IntegrationServer).Export(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Integration/Export",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IntegrationServer).Export(ctx, req.(*IntegrationExportReq))
	}
	return interceptor(ctx, in, info, handler)
}

var _Integration_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.Integration",
	HandlerType: (*IntegrationServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Init",
			Handler:    _Integration_Init_Handler,
		},
		{
			MethodName: "Export",
			Handler:    _Integration_Export_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "defs.proto",
}

// AgentClient is the client API for Agent service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type AgentClient interface {
	ExportStarted(ctx context.Context, in *ExportStartedReq, opts ...grpc.CallOption) (*ExportStartedResp, error)
	ExportDone(ctx context.Context, in *ExportDoneReq, opts ...grpc.CallOption) (*Empty, error)
	SendExported(ctx context.Context, in *SendExportedReq, opts ...grpc.CallOption) (*Empty, error)
	ExportGitRepo(ctx context.Context, in *ExportGitRepoReq, opts ...grpc.CallOption) (*Empty, error)
}

type agentClient struct {
	cc *grpc.ClientConn
}

func NewAgentClient(cc *grpc.ClientConn) AgentClient {
	return &agentClient{cc}
}

func (c *agentClient) ExportStarted(ctx context.Context, in *ExportStartedReq, opts ...grpc.CallOption) (*ExportStartedResp, error) {
	out := new(ExportStartedResp)
	err := c.cc.Invoke(ctx, "/proto.Agent/ExportStarted", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentClient) ExportDone(ctx context.Context, in *ExportDoneReq, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := c.cc.Invoke(ctx, "/proto.Agent/ExportDone", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentClient) SendExported(ctx context.Context, in *SendExportedReq, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := c.cc.Invoke(ctx, "/proto.Agent/SendExported", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentClient) ExportGitRepo(ctx context.Context, in *ExportGitRepoReq, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := c.cc.Invoke(ctx, "/proto.Agent/ExportGitRepo", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AgentServer is the server API for Agent service.
type AgentServer interface {
	ExportStarted(context.Context, *ExportStartedReq) (*ExportStartedResp, error)
	ExportDone(context.Context, *ExportDoneReq) (*Empty, error)
	SendExported(context.Context, *SendExportedReq) (*Empty, error)
	ExportGitRepo(context.Context, *ExportGitRepoReq) (*Empty, error)
}

func RegisterAgentServer(s *grpc.Server, srv AgentServer) {
	s.RegisterService(&_Agent_serviceDesc, srv)
}

func _Agent_ExportStarted_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ExportStartedReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServer).ExportStarted(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Agent/ExportStarted",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServer).ExportStarted(ctx, req.(*ExportStartedReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Agent_ExportDone_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ExportDoneReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServer).ExportDone(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Agent/ExportDone",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServer).ExportDone(ctx, req.(*ExportDoneReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Agent_SendExported_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SendExportedReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServer).SendExported(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Agent/SendExported",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServer).SendExported(ctx, req.(*SendExportedReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Agent_ExportGitRepo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ExportGitRepoReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServer).ExportGitRepo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Agent/ExportGitRepo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServer).ExportGitRepo(ctx, req.(*ExportGitRepoReq))
	}
	return interceptor(ctx, in, info, handler)
}

var _Agent_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.Agent",
	HandlerType: (*AgentServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ExportStarted",
			Handler:    _Agent_ExportStarted_Handler,
		},
		{
			MethodName: "ExportDone",
			Handler:    _Agent_ExportDone_Handler,
		},
		{
			MethodName: "SendExported",
			Handler:    _Agent_SendExported_Handler,
		},
		{
			MethodName: "ExportGitRepo",
			Handler:    _Agent_ExportGitRepo_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "defs.proto",
}
