// Code generated by protoc-gen-go. DO NOT EDIT.
// source: defs.proto

package proto

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type ExportObj_DataType int32

const (
	ExportObj_JSON ExportObj_DataType = 0
	ExportObj_AVRO ExportObj_DataType = 1
)

var ExportObj_DataType_name = map[int32]string{
	0: "JSON",
	1: "AVRO",
}

var ExportObj_DataType_value = map[string]int32{
	"JSON": 0,
	"AVRO": 1,
}

func (x ExportObj_DataType) String() string {
	return proto.EnumName(ExportObj_DataType_name, int32(x))
}

func (ExportObj_DataType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_bf10f51bd2cb5547, []int{3, 0}
}

type Empty struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Empty) Reset()         { *m = Empty{} }
func (m *Empty) String() string { return proto.CompactTextString(m) }
func (*Empty) ProtoMessage()    {}
func (*Empty) Descriptor() ([]byte, []int) {
	return fileDescriptor_bf10f51bd2cb5547, []int{0}
}

func (m *Empty) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Empty.Unmarshal(m, b)
}
func (m *Empty) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Empty.Marshal(b, m, deterministic)
}
func (m *Empty) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Empty.Merge(m, src)
}
func (m *Empty) XXX_Size() int {
	return xxx_messageInfo_Empty.Size(m)
}
func (m *Empty) XXX_DiscardUnknown() {
	xxx_messageInfo_Empty.DiscardUnknown(m)
}

var xxx_messageInfo_Empty proto.InternalMessageInfo

type IntegrationInitReq struct {
	ServerId             uint32   `protobuf:"varint,1,opt,name=server_id,json=serverId,proto3" json:"server_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *IntegrationInitReq) Reset()         { *m = IntegrationInitReq{} }
func (m *IntegrationInitReq) String() string { return proto.CompactTextString(m) }
func (*IntegrationInitReq) ProtoMessage()    {}
func (*IntegrationInitReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_bf10f51bd2cb5547, []int{1}
}

func (m *IntegrationInitReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_IntegrationInitReq.Unmarshal(m, b)
}
func (m *IntegrationInitReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_IntegrationInitReq.Marshal(b, m, deterministic)
}
func (m *IntegrationInitReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_IntegrationInitReq.Merge(m, src)
}
func (m *IntegrationInitReq) XXX_Size() int {
	return xxx_messageInfo_IntegrationInitReq.Size(m)
}
func (m *IntegrationInitReq) XXX_DiscardUnknown() {
	xxx_messageInfo_IntegrationInitReq.DiscardUnknown(m)
}

var xxx_messageInfo_IntegrationInitReq proto.InternalMessageInfo

func (m *IntegrationInitReq) GetServerId() uint32 {
	if m != nil {
		return m.ServerId
	}
	return 0
}

type SendExportedReq struct {
	Objs                 []*ExportObj `protobuf:"bytes,1,rep,name=objs,proto3" json:"objs,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *SendExportedReq) Reset()         { *m = SendExportedReq{} }
func (m *SendExportedReq) String() string { return proto.CompactTextString(m) }
func (*SendExportedReq) ProtoMessage()    {}
func (*SendExportedReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_bf10f51bd2cb5547, []int{2}
}

func (m *SendExportedReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SendExportedReq.Unmarshal(m, b)
}
func (m *SendExportedReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SendExportedReq.Marshal(b, m, deterministic)
}
func (m *SendExportedReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SendExportedReq.Merge(m, src)
}
func (m *SendExportedReq) XXX_Size() int {
	return xxx_messageInfo_SendExportedReq.Size(m)
}
func (m *SendExportedReq) XXX_DiscardUnknown() {
	xxx_messageInfo_SendExportedReq.DiscardUnknown(m)
}

var xxx_messageInfo_SendExportedReq proto.InternalMessageInfo

func (m *SendExportedReq) GetObjs() []*ExportObj {
	if m != nil {
		return m.Objs
	}
	return nil
}

type ExportObj struct {
	DataType             ExportObj_DataType `protobuf:"varint,1,opt,name=data_type,json=dataType,proto3,enum=proto.ExportObj_DataType" json:"data_type,omitempty"`
	Data                 []byte             `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *ExportObj) Reset()         { *m = ExportObj{} }
func (m *ExportObj) String() string { return proto.CompactTextString(m) }
func (*ExportObj) ProtoMessage()    {}
func (*ExportObj) Descriptor() ([]byte, []int) {
	return fileDescriptor_bf10f51bd2cb5547, []int{3}
}

func (m *ExportObj) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ExportObj.Unmarshal(m, b)
}
func (m *ExportObj) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ExportObj.Marshal(b, m, deterministic)
}
func (m *ExportObj) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ExportObj.Merge(m, src)
}
func (m *ExportObj) XXX_Size() int {
	return xxx_messageInfo_ExportObj.Size(m)
}
func (m *ExportObj) XXX_DiscardUnknown() {
	xxx_messageInfo_ExportObj.DiscardUnknown(m)
}

var xxx_messageInfo_ExportObj proto.InternalMessageInfo

func (m *ExportObj) GetDataType() ExportObj_DataType {
	if m != nil {
		return m.DataType
	}
	return ExportObj_JSON
}

func (m *ExportObj) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

func init() {
	proto.RegisterEnum("proto.ExportObj_DataType", ExportObj_DataType_name, ExportObj_DataType_value)
	proto.RegisterType((*Empty)(nil), "proto.Empty")
	proto.RegisterType((*IntegrationInitReq)(nil), "proto.IntegrationInitReq")
	proto.RegisterType((*SendExportedReq)(nil), "proto.SendExportedReq")
	proto.RegisterType((*ExportObj)(nil), "proto.ExportObj")
}

func init() { proto.RegisterFile("defs.proto", fileDescriptor_bf10f51bd2cb5547) }

var fileDescriptor_bf10f51bd2cb5547 = []byte{
	// 276 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x64, 0x90, 0xc1, 0x4b, 0xb4, 0x50,
	0x14, 0xc5, 0x3f, 0xbf, 0x74, 0xd2, 0x3b, 0x56, 0x72, 0x17, 0x61, 0x05, 0x21, 0x32, 0x0b, 0x57,
	0x46, 0x16, 0xb5, 0x6a, 0x31, 0xd0, 0x2c, 0x6c, 0x91, 0xf0, 0x26, 0xda, 0x0e, 0xca, 0xbb, 0x0d,
	0x0e, 0xa4, 0xa6, 0x97, 0xca, 0xff, 0x3e, 0x7c, 0x8e, 0x31, 0x4e, 0x2b, 0x8f, 0xe7, 0xfd, 0x2e,
	0xe7, 0xde, 0x03, 0x20, 0xe9, 0xad, 0x09, 0xab, 0xba, 0xe4, 0x12, 0x0d, 0xf5, 0xf1, 0x0f, 0xc1,
	0x58, 0xbc, 0x57, 0xdc, 0xfa, 0xd7, 0x80, 0x71, 0xc1, 0xb4, 0xae, 0x53, 0xce, 0xcb, 0x22, 0x2e,
	0x72, 0x16, 0xf4, 0x81, 0x17, 0x60, 0x35, 0x54, 0x7f, 0x52, 0xbd, 0xca, 0xa5, 0xab, 0x79, 0x5a,
	0x70, 0x24, 0xcc, 0xde, 0x88, 0xa5, 0x7f, 0x0f, 0x27, 0x4b, 0x2a, 0xe4, 0xe2, 0xbb, 0x2a, 0x6b,
	0x26, 0xd9, 0xf1, 0x33, 0xd0, 0xcb, 0x6c, 0xd3, 0xb8, 0x9a, 0x77, 0x10, 0x4c, 0x23, 0xa7, 0xcf,
	0x0a, 0x7b, 0x22, 0xc9, 0x36, 0x42, 0xbd, 0xfa, 0x5f, 0x60, 0xfd, 0x5a, 0x78, 0x07, 0x96, 0x4c,
	0x39, 0x5d, 0x71, 0x5b, 0x91, 0x8a, 0x38, 0x8e, 0xce, 0xf6, 0xe7, 0xc2, 0xc7, 0x94, 0xd3, 0x97,
	0xb6, 0x22, 0x61, 0xca, 0xad, 0x42, 0x04, 0xbd, 0xd3, 0xee, 0x7f, 0x4f, 0x0b, 0x6c, 0xa1, 0xb4,
	0x7f, 0x09, 0xe6, 0x40, 0xa2, 0x09, 0xfa, 0xd3, 0x32, 0x79, 0x76, 0xfe, 0x75, 0x6a, 0xfe, 0x2a,
	0x12, 0x47, 0x8b, 0x24, 0x4c, 0x77, 0x8e, 0xc4, 0x2b, 0xd0, 0xbb, 0x43, 0x71, 0xc8, 0xfb, 0x5b,
	0xc0, 0xb9, 0x3d, 0xac, 0xd2, 0x95, 0x84, 0x33, 0x98, 0xf4, 0x3b, 0xe1, 0xc8, 0x1f, 0x53, 0xd1,
	0x03, 0x18, 0xf3, 0x35, 0x15, 0x8c, 0xb7, 0x60, 0xef, 0x16, 0x84, 0xa7, 0x5b, 0x6c, 0xaf, 0xb5,
	0xf1, 0x78, 0x36, 0x51, 0x3f, 0x37, 0x3f, 0x01, 0x00, 0x00, 0xff, 0xff, 0x2e, 0x89, 0x23, 0xde,
	0xae, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// IntegrationClient is the client API for Integration service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type IntegrationClient interface {
	Init(ctx context.Context, in *IntegrationInitReq, opts ...grpc.CallOption) (*Empty, error)
	Export(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Empty, error)
}

type integrationClient struct {
	cc *grpc.ClientConn
}

func NewIntegrationClient(cc *grpc.ClientConn) IntegrationClient {
	return &integrationClient{cc}
}

func (c *integrationClient) Init(ctx context.Context, in *IntegrationInitReq, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := c.cc.Invoke(ctx, "/proto.Integration/Init", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *integrationClient) Export(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := c.cc.Invoke(ctx, "/proto.Integration/Export", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// IntegrationServer is the server API for Integration service.
type IntegrationServer interface {
	Init(context.Context, *IntegrationInitReq) (*Empty, error)
	Export(context.Context, *Empty) (*Empty, error)
}

func RegisterIntegrationServer(s *grpc.Server, srv IntegrationServer) {
	s.RegisterService(&_Integration_serviceDesc, srv)
}

func _Integration_Init_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IntegrationInitReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IntegrationServer).Init(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Integration/Init",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IntegrationServer).Init(ctx, req.(*IntegrationInitReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Integration_Export_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IntegrationServer).Export(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Integration/Export",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IntegrationServer).Export(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

var _Integration_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.Integration",
	HandlerType: (*IntegrationServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Init",
			Handler:    _Integration_Init_Handler,
		},
		{
			MethodName: "Export",
			Handler:    _Integration_Export_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "defs.proto",
}

// AgentClient is the client API for Agent service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type AgentClient interface {
	SendExported(ctx context.Context, in *SendExportedReq, opts ...grpc.CallOption) (*Empty, error)
}

type agentClient struct {
	cc *grpc.ClientConn
}

func NewAgentClient(cc *grpc.ClientConn) AgentClient {
	return &agentClient{cc}
}

func (c *agentClient) SendExported(ctx context.Context, in *SendExportedReq, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := c.cc.Invoke(ctx, "/proto.Agent/SendExported", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AgentServer is the server API for Agent service.
type AgentServer interface {
	SendExported(context.Context, *SendExportedReq) (*Empty, error)
}

func RegisterAgentServer(s *grpc.Server, srv AgentServer) {
	s.RegisterService(&_Agent_serviceDesc, srv)
}

func _Agent_SendExported_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SendExportedReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServer).SendExported(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Agent/SendExported",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServer).SendExported(ctx, req.(*SendExportedReq))
	}
	return interceptor(ctx, in, info, handler)
}

var _Agent_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.Agent",
	HandlerType: (*AgentServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SendExported",
			Handler:    _Agent_SendExported_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "defs.proto",
}
